/** Minimal Lua serialization for the generated tables. */

export function luaString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

export function luaValue(value: unknown): string {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return Number.isInteger(value) ? String(value) : String(value);
  if (typeof value === "string") return luaString(value);
  if (Array.isArray(value)) return `{ ${value.map(luaValue).join(", ")} }`;
  if (value === null || value === undefined) return "nil";
  throw new TypeError(`cannot serialize ${String(value)}`);
}

/** `key = value,` lines for the defined fields of an object, in the given order. */
export function luaFields(obj: Record<string, unknown>, fields: string[], indent = "    "): string[] {
  return fields.filter((f) => obj[f] !== undefined && obj[f] !== null).map((f) => `${indent}${f} = ${luaValue(obj[f])},`);
}

export function header(source: string): string {
  return `-- Generated by .contribute/tools (npm run gen) from ${source} - do not edit.\n`;
}
