/** Minimal Lua serialization for the generated tables. */

export function luaString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

export function luaValue(value: unknown): string {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return Number.isInteger(value) ? String(value) : String(value);
  if (typeof value === "string") return luaString(value);
  if (Array.isArray(value)) return `{ ${value.map(luaValue).join(", ")} }`;
  if (value === null || value === undefined) return "nil";
  if (typeof value === "object") {
    // Plain object with identifier keys (the stats table): `{ INTELLECT = 4, SPELL_POWER = 18 }`, sorted.
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined && v !== null)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([k, v]) => `${luaKey(k)} = ${luaValue(v)}`);
    return entries.length > 0 ? `{ ${entries.join(", ")} }` : "{}";
  }
  throw new TypeError(`cannot serialize ${String(value)}`);
}

function luaKey(key: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? key : `[${luaString(key)}]`;
}

/** `key = value,` lines for the defined fields of an object, in the given order. */
export function luaFields(obj: Record<string, unknown>, fields: string[], indent = "    "): string[] {
  return fields
    .filter((f) => obj[f] !== undefined && obj[f] !== null)
    .map((f) => `${indent}${f} = ${luaValue(obj[f])},`);
}

export function header(source: string): string {
  return `-- Generated by .contribute/tools (npm run gen) from ${source} - do not edit.\n`;
}
