-- Type annotations only; this file is not listed in the TOC and never runs in-game.
-- It exists so the Lua language server can type the `...` vararg every file receives.
-- Every file should start with:
--   ---@type string, ForeverLoot
--   local appName, app = ...
-- When a file adds something to `app`, add a matching ---@field here.

---@class ForeverLoot
---@field logger ForeverLoot.Logger
---@field addon ForeverLoot.Addon
---@field dbDefaults ForeverLoot.DBDefaults
---@field db ForeverLoot.DB

-- The AceDB object. Profile/char/global mirror the shape of app.dbDefaults.
---@class ForeverLoot.DB
---@field profile ForeverLoot.DB.Profile
---@field char ForeverLoot.DB.Char
---@field global ForeverLoot.DB.Global
---@field RegisterCallback fun(target: table, event: string, method: string|function)
---@field GetCurrentProfile fun(self: ForeverLoot.DB): string
---@field SetProfile fun(self: ForeverLoot.DB, name: string)
---@field ResetProfile fun(self: ForeverLoot.DB)

-- Subset of the AceAddon-3.0 / AceConsole-3.0 / AceEvent-3.0 API the addon uses.
-- lib/ is excluded from the language server, so these are declared by hand.
---@class ForeverLoot.Addon
---@field db ForeverLoot.DB
---@field Print fun(self: ForeverLoot.Addon, ...: any)
---@field GetArgs fun(self: ForeverLoot.Addon, input: string, numArgs?: integer, startPos?: integer): ...
---@field RegisterChatCommand fun(self: ForeverLoot.Addon, command: string, handler: string|function, persist?: boolean)
---@field RegisterEvent fun(self: ForeverLoot.Addon, event: string, handler?: string|function, ...: any)
---@field UnregisterEvent fun(self: ForeverLoot.Addon, event: string)
---@field UnregisterAllEvents fun(self: ForeverLoot.Addon)
